codecov:
  require_ci_to_pass: true
  bot: "codecov-io"
  max_report_age: 24h
  disable_default_path_fixes: false

coverage:
  precision: 2
  round: down
  range: "100...100"
  
  status:
    project:
      default:
        target: 100%
        threshold: 0%
        base: auto
        if_not_found: failure
        if_ci_failed: error
        informational: false
        only_pulls: false
    
    patch:
      default:
        target: 100%
        threshold: 0%
        base: auto
        if_not_found: failure
        if_ci_failed: error
        informational: false
        only_pulls: false

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      method: false
      macro: false

comment:
  layout: "reach,diff,flags,tree,betaprofiling"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true
  hide_project_coverage: false
  after_n_builds: 1

ignore:
  - "tests/**/*"
  - "**/__init__.py"
  - "**/test_*.py"
  - "**/*_test.py"
  - "setup.py"
  - "main.py"
  - "static/**/*"
  - "src/view/**/*"

flags:
  unittests:
    paths:
      - src/
      - config/
    carryforward: true
    target: 100%